### ISSUE TITLE
Landingpages disappear

### ISSUE THREAD

**Issue by jspoe** [EmicoEcommerce/Magento2AttributeLandingTweakwise#13]
Hi,

We have a client that uses the attribute landing pages module on Magento 2.4.6-p3 Commerce, with version 4.2.1 of this module.
I know, we're a couple of versions behind, but couldn't find something related in the latest versions either.

The issue is that every once in a while, pages disappear. They are then completely deleted from the database, except for the url_rewrite.
First we thought this might have been an user error, later we thought of the foreign key between the landingspage and the category. However, this category still exists and there are pages that are also linked to this category that weren't deleted.

Is someone familiar with this issue? Things I could think of:
- Scheduled change of category in commerce / row_id vs. entity_id
- Foreign key between landingspage and category

As far as I could see, no errors in the logs, also no admin action reports that suggested a delete.
Let me know if you want more information.

**Comment by ahuininga-orisha** [comment]
@jspoe I'm not familiar with this issue. But i might be able to help narrow down the cause.

- Are you sure the pages where in the database? I've had some weird issues while testing that (sometimes) the landingpage was working (in cache) but the page wasn't in the database. I've always thought i've caused the issue myself while testing and can't reproduce it on an clean install. But it may be related to your issue.
- Is it possible its happening while deleting another landingpage? 2 pages get deleted instead of one?
- Do the deleted pages have something in common? For example where they all inactive? Or for the same category?
- Where they linked to an overviewpage Which has been deleted?

**Comment by jspoe** [comment]
Hi @ah-net 

Thank you for the reply, I asked the client and today this happened again, but that confirmed my thoughts that it has something to do with scheduled changes of categories.

- Are you sure the pages where in the database? I've had some weird issues while testing that (sometimes) the landingpage was working (in cache) but the page wasn't in the database. I've always thought i've caused the issue myself while testing and can't reproduce it on an clean install. But it may be related to your issue.
>> Yes, the pages were there, we also see them in the backups of the databases.

- Is it possible its happening while deleting another landingpage? 2 pages get deleted instead of one?
>> The client is not aware of pages that were deleted the last days. So I doubt it. In my backups of the database I have the same amount of records as of until today.

- Do the deleted pages have something in common? For example where they all inactive? Or for the same category?
>> Yes, they all had a scheduled category update that the client added yesterday for next week. 

![scheduled_categories](https://github.com/EmicoEcommerce/Magento2AttributeLandingTweakwise/assets/1849310/8dd9c20e-6c0c-410a-81af-18b5d3c408af)

- Where they linked to an overviewpage Which has been deleted?
>> No, the client does not uses overview pages

**Comment by YouriGuapa** [comment]
Hi @ah-net,

Do you have any update regarding this issue.

Thanks in advance.

**Comment by YouriGuapa** [comment]
Hi @ah-net,

Our mutual client is creating many attribute landing pages in preparation for Black Friday. To ensure that they don’t miss out on revenue on this crucial day, it is essential that no bugs or disruptions occur.

Could you please address the above issue urgently? Can you tell me something about timelines?

Kind regards,

Youri Schepel
Managing Director Guapa

**Comment by ahuininga-orisha** [comment]
@YouriGuapa I'll discuss it internally and get back to you on this tomorrow.

**Comment by ahuininga-orisha** [comment]
@YouriGuapa @jspoe I'll debug this issue today. I'll give you an status update end of day tomorrow

**Comment by ahuininga-orisha** [comment]
@jspoe @YouriGuapa I did some tests and the only reason that the landingpages can disappear is if the category is deleted. 

However this doesn't seem to happen to me if I schedule an category change. Can you check what happens in the following cases?

- When you schedule an design change, does the category id change or is the category (temporary) deleted?
- Does the problem still occur if you remove the foreign key for category id on the emico_attirbute_landingpage table and you schedule an design change?
- Is it possible that another process (temperory) deletes the categories?

**Comment by Guapa-development** [comment]
Hi @ah-net 

- When you schedule a design change, does the category id change or is the category (temporary) deleted?
>> No, not that we are aware of, the ID at least does not change and the 'created_at' dates are also in the past. So unless the entity is completely duplicated with all data, this seems not to occur. 

- Does the problem still occur if you remove the foreign key for category id on the emico_attirbute_landingpage table and you schedule a design change?
>> Will try this suggestion on the staging today

- Is it possible that another process (temporary) deletes the categories?
>> Have looked into the custom code, but could not find references to any category delete. The client uses API's and a PIM to control this, so I also looked in the access logs from the past month and haven't seen any endpoints to the API that requests a delete. Like said in the first bullet, also looked into the 'created_at' date of the categories of ALP's that were deleted and they are way in the past (2 categories added in 2023, others in 2022 or before)

**Comment by ahuininga-orisha** [comment]
@jspoe @YouriGuapa @Guapa-development Did the problem still occur when removing the foreign key?

**Comment by jspoe** [comment]
Hi @ah-net I removed the foreign key yesterday on the staging and did some scheduled changes for overnight.
The pages did not disappear, so I removed the foreign key on production to see if the pages disappear when the changes for next week are being applied.

I'll keep you up to date. Thanks!

**Comment by jspoe** [comment]
Hi @ah-net 

Scheduled category changes went live this morning without the pages disappearing. So either the foreign key removal worked or the issue is not related to the scheduled changes.

Let's just keep an aye on it for know, shall I raise another ticket and reference to this one if it still happens?
