### ISSUE TITLE
Plugin on protected function

### ISSUE THREAD

**Issue by mischabraam** [EmicoEcommerce/Magento2AttributeLandingTweakwise#3]
https://github.com/EmicoEcommerce/Magento2AttributeLandingTweakwise/blob/697fef962813498bd08e44998ca1db301e69cba3/src/Plugin/Seo/FilterHelperPlugin.php#L59

Above is a declaration of an around plugin upon a protected function.

https://github.com/EmicoEcommerce/Magento2Tweakwise/blob/4e34c65f1c39be5c57d6a6f993dc271ef4dd07f4/Model/Seo/FilterHelper.php#L211

I'm not sure what this plugin should do, but this plugin probably doesn't do its job.

**Comment by ahuininga-orisha** [comment]
The function seems to have something to do with the robot.txt and the indexing of filters. But i'm not sure exactly what is supposed to do. I can fix the plugin issue, but i don't want to fix something when i'm not sure exactly what is should do.

@bramstroker @edwinljacobs Do you have any idea what the function should do?
